spring:
  jpa:
    hibernate:
      ddl-auto: ${jpa.ddl-auto:create}
  datasource:
    url: jdbc:mysql://${datasource.host:127.0.0.1}:${datasource.port:8889}/spring?useUnicode=true&characterEncoding=utf-8
    username: ${datasource.username:root}
    password: ${datasource.password:root}